allowBuilds:
  '@parcel/watcher': true
  argon2: true
  better-sqlite3: true
  esbuild: true
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - musl
    - glibc
